version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    reviewers:
      - "kirill-oliinyk"
    ignore:
      - dependency-name: "*"
        versions: ["*"]
    automerge:
      branch: main
      rebase: true
      ignore_requirement_updates: true
