require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-faker
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.1.3
  TargetRailsVersion: 7.1.3
  NewCops: enable

# ===================== Style ====================
Style/NumericPredicate:
  Enabled: false
Style/Documentation:
  Enabled: true
  Exclude:
    - config/**/*
    - db/**/*
    - app/models/application_record.rb
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
Style/SymbolProc:
  Enabled: true
  Exclude:
    - db/**/*
# ===================== Metrics ====================
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/**/*
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - db/**/*
    - config/**/*
    - app/admin/**
    - lib/tasks/auto_annotate_models.rake
# ===================== Metrics ====================
Rails/RakeEnvironment:
  Enabled: true
  Exclude:
    - /lib/tasks/auto_annotate_models.rake
# ===================== RSpec ====================
RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Exclude:
    - spec/services/resources/publishable/get_for_show_page_spec.rb
    - spec/services/resources/publishable/get_for_index_page_spec.rb
RSpec/NestedGroups:
  Max: 4
# ===================== Rails ====================
Rails/DynamicFindBy:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Enabled: true
  Exclude:
    - db/migrate/20240827130125_create_categories_products.rb
