name: CI

on:
  push:
    branches: ['main']
  pull_request_target:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}

jobs:
  rspec:
    runs-on: ubuntu-20.04
    services:
      db:
        image: postgres:16-alpine
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "happy_parents_ua_test", "-U", "rails"]
          interval: 10s
          timeout: 5s
          retries: 5
      redis:
        image: redis:alpine
        ports:
          - '6379:6379'

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@db:5432/happy_parents_ua_test"
      REDIS_URL: redis://localhost:6379/0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup db schema
        run: bundle exec rake db:create db:schema:load --trace

      - name: Run rspec
        run: bundle exec rspec --format progress
